#!/bin/bash

if [ -z "$1" ]
then
    echo "Usage: code_init [branch]"
    exit 1 
fi

project=$(basename $PWD)
branch="$1"
branchdir="../../$branch"

[ ! -d "$branchdir" ] && mkdir -p "$branchdir"

projectdir=$branchdir/$project

if [ ! -d "$projectdir" ]
then
    echo "Initializing worktree for $project:$branch..."
    git worktree add "$projectdir" "$branch"
fi

code "$branchdir/$branch.code-workspace"
