#!/bin/bash

branch=$(git branch --show-current --no-color)
module=$(basename $PWD)
remote="$(git rev-parse --abbrev-ref --symbolic-full-name @{u})"
remote_branch=${remote#*"/"}
remote=${remote%%"/"*}
push_remote="$remote"
[[ $push_remote = "origin" ]] && push_remote="gerrit"

case "$1" in
  --branch)
    shift
    branch=$1
    shift
    ;;
esac

if [ -z "$branch" ]
then
    >&2 echo "fatal: Can't identify which branch to push to"
    exit 1
fi

sha="$*"

repository=$(git rev-parse --git-dir)
repository=${repository%/\.git/worktrees*}
repository=${repository%/worktrees/$module}

if [[ $repository =~ .git/modules/$module ]]
then
  repository=${repository%/\.git/modules/$module/worktrees*}
  repository=${repository}/${module}
fi

if [ -z "$1" ]
then
    sha=$branch
fi

remote=$(git remote | grep $remote)

if [ -z "$remote" ]
then
    remote="gerrit"
fi

count=$(git rev-list --count $remote/$remote_branch...$branch)
error=0

if [ "$count" -gt 1 ]
then
  cd $repository
  git checkout $remote/$branch 2> /dev/null
  git reset --hard $remote/$branch
  git cherry-pick $sha
  error=$?
fi

if [ "$error" -eq 0 ]
then
  echo "Pushing to $push_remote/$remote_branch..."
  git log --oneline $remote/$remote_branch...
  git push $push_remote HEAD:refs/for/$remote_branch
fi
